# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Gleam contributors

[package]
name = "geam-gleam-erlang-term-format"
authors = ["Louis Pilfold <louis@lpil.uk>"]
version = "1.18.1-geam.2"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/panarch/gleam"
description = "Gleam's Erlang term formatter, packaged for Geam"
readme = "README.geam.md"
publish = ["crates-io"]

[dependencies]
num-bigint.workspace = true
num-traits.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[lib]
name = "erlang_term_format"
